# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:zwj...01@tcp(172.17.0.10:3306)/go-gateway?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100